---

- name: Test Provisioning Ubuntu
  hosts: all
  remote_user: "$USER"
  gather_facts: yes

  tasks:
  - name: Download YAUP
    git:
      repo: https://github.com/JEA666/yaup.git
      dest: ~/git/pri/

  - name: Press Play on Tape
    shell: cd ~/git/pri/yaup && ansible-playbook ubuntudesktop.yml --ask-become-pass