---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - vars/pri_global.yml
#    - vars/pub_global.yml
  roles:
    - common
    - gen_ssh_key
    - setup_git
    - atom
    - slack
    - spk_config
    - oh-my-zsh

- name: Cleaning Ubuntu
  hosts: local
  connection: local
  become: yes
  become_user: root
  gather_facts: no
  tasks:

    - name: Removing .deb from /tmp
      shell: rm -f /tmp/*.deb*

    - name: If dell-super-key is present
      apt:
        name: dell-super-key
        state: absent
