---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - vars/pri_global.yml
#    - vars/pub_global.yml
  roles:
    - common
    - jdk8
    - gen_ssh_key   # Done
    - setup_git
    - spk_config     # Done
    - docker
    - docker-machine
#    - citrix_rec
#    - vmware_client
    - oh-my-zsh
    - atom
    - slack
#    - clean-install

- name: Cleaning Ubuntu
  hosts: local
  connection: local
  become: yes
  become_user: root
  gather_facts: no
  tasks:

    # - name: Removing .deb from /tmp
    #   shell: rm -f /tmp/{atom-amd64.deb,slack-desktop.deb}

    - name: If dell-super-key is present
      apt:
        name: dell-super-key
        state: absent
