---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
          #    - inventory/local/group_vars/
    - inventory/local/host_vars/localApps 
    - inventory/local/host_vars/userVars
    - inventory/local/host_vars/priHost    

  roles:
    - test
#    - sysTools
#    - devTools
    - secTools
#    - setup_git
#    - shellEnv
      # - docker
      # - slack
      # - virtualbox
      # - docker-machine
      # - oh-my-zsh
#    - clean-install
