---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - inventory/local/host_vars/localApps 
    - inventory/local/host_vars/userVars
    - inventory/local/host_vars/priHost    
  ignore_errors: true

  roles:
    - testForApps
    - sysTools
    - devTools
    - secTools
#    - setup_git
    - shellEnv
    - clean-install
