---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - inventory/local/host_vars/localApps 
    - inventory/local/host_vars/userVars
    - inventory/local/host_vars/priHost    
  ignore_errors: true

  roles:
    - testForApps
    - sysTools
    - iptables
    - shellEnv
    - secTools
    - devTools
#    - setup_git  #Rune once, need to check for config and make a solution for work config.
    - clean-install
 