---

- name: Provisioning Ubuntu
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - vars/pri_global.yml   

  roles:
    - common
    - gen_ssh_key
    - setup_git
    - docker
    - slack
    - virtualbox
    - docker-machine
    - oh-my-zsh

    - clean-install
