---

- name: System Tools
  block:
 
    - name: Install
      apt:
        name: "{{ aptSysTools }}"
        state: present
    
    - name: Download and install libiperf
      apt:
        deb: https://iperf.fr/download/ubuntu/libiperf0_3.1.3-1_amd64.deb
    
    - name: Download and install libiperf
      apt:
        deb: https://iperf.fr/download/ubuntu/iperf3_3.1.3-1_amd64.deb

    - name: Upgrade installed packages
      apt: upgrade=yes

  become: yes
  become_user: root
