---
# tasks file for jdk8

- name: Download jdk8u162
    command: wget -O /tmp/jdk8u162-amd64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.tar.gz
    args:
      creates: "/tmp/jdk8u162-amd64.tar.gz"
