---
# tasks file for oh-my-zsh
- name: Check for zsh text editor
  command: dpkg-query -W zsh
  register: zsh_exists
  failed_when: false
  changed_when: false

- name: Install zsh
  become: yes
  become_user: root
  apt:
    name: zsh
    state: present
  when: zsh_exists.rc ==1

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  when: zsh_exists.rc == 1

- name: Copy .zshrc to $HOME
  template:
    src: zshrc
    dest: ~/.zshrc
  when: zsh_exists.rc == 1

- name: Switch to ZSH
  become: yes
  become_user: root
  user:
    name: "{{user_name}}"
    shell: /usr/bin/zsh
  when: zsh_exists.rc == 0





# - name: Download Ubuntu oh-my-zsh package
#   command: "wget -O /tmp/oh-my-zsh.deb https://github.com/atom/atom/releases/download/{{ atom_version }}/atom-amd64.de"
#   args:
#     creates: "/tmp/atom-amd64.deb"
#   when: zsh_exists.rc == 1
#
# - name: Instaling Atom text editor
#   become: yes
#   become_user: root
#   apt:
#     deb: /tmp/atom-amd64.deb
#   when: atom_exists.rc == 1
