---
# tasks file for oh-my-zsh
- name: Pre install ZSH - Check for shell
  command: dpkg-query -W zsh
  register: zsh_exists
  failed_when: false
  changed_when: false

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: zsh_exists.rc == 1

- name: Copy .zshrc to $HOME
  template:
    src: zshrc
    dest: ~/.zshrc
  when: zsh_exists.rc == 1

- name: Post install ZSH - Switch shell  # Works privat/ not at work
  become: yes
  become_user: root
  user:
    name: "{{user_name}}"
    shell: /usr/bin/zsh
  when: zsh_exists.rc == 1
