
# - name: Check for Gittyleaks
#   shell: which gittyleaks
#   register: gotGitty

- name: Download and install Gittyleaks
  pip:
    name: gittyleaks
    executable: pip3
  become: yes
  become_user: root
  when: gotGitty.rc !=0

- name: Download BFG Repo-Cleaner
  get_url:
    url: https://search.maven.org/classic/remote_content?g=com.madgag&a=bfg&v=LATEST
    dest: /usr/local/bin/bfg.jar
  become: yes
  become_user: root
  when: gotBfg.stat.exists == False

- name: Install Iptables Raw
  git:
    repo: https://github.com/Nordeus/ansible_iptables_raw.git
    dest: /usr/share/ansible/plugins/modules/ansible_iptables_raw
  when: gotIptRaw.stat.exists == False