---

- name: Check for Atom text editor
  command: dpkg-query -W atom
  register: atom_exists
  failed_when: false
  changed_when: false

- name: Download Ubuntu atom package
  command: "wget -O /tmp/atom-amd64.deb https://github.com/atom/atom/releases/download/{{ atom_version }}/atom-amd64.deb"
  args:
    creates: "/tmp/atom-amd64.deb"
  when: atom_exists.rc == 1

- name: Instaling Atom text editor
  become: yes
  become_user: root
  apt:
    deb: /tmp/atom-amd64.deb
  when: atom_exists.rc == 1
