---

- name: Pre install -- Check for Atom text editor
  command: dpkg-query -W atom
  register: atom_exists
  failed_when: false
  changed_when: false

- name: Pre install JDK - Download jdk8u161
  get_url:
    url: "{{ atom_url_deb }}{{ atom_version }}{{ atom_trailer }}"
    dest: "{{ atom_tmp_deb }}"
  when: atom_exists.rc == 1

# - name: Download Ubuntu atom package
#   command: "wget -O /tmp/atom-amd64.deb https://github.com/atom/atom/releases/download/{{ atom_version }}/atom-amd64.deb"
#   args:
#     creates: "/tmp/atom-amd64.deb"
#   when: atom_exists.rc == 1

- name: Install Atom text editor
  become: yes
  become_user: root
  apt:
    deb: /tmp/atom-amd64.deb
  when: atom_exists.rc == 1
