---

- name: Common packages
  block:
    - name: Install
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - htop
        - iftop
        - vim
        - autofs
        - virtualbox
        - tree
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - gdebi-core
        - zsh
        - glances
        - xbacklight
  #      - npm

    - name: Upgrade installed packages
      apt: upgrade=yes
  become: yes
  become_user: root
