---
# tasks file for docker
- name: pre install Docker - Check for old version and remove
  become: yes
  become_user: root
  apt:
    name: "{{ item.deb }}"
    state: absent
  with_items:
    - { deb: docker }
    - { deb: docker-engine }
    - { deb: docker.io }

- name: pre install Docker - add key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
#    keyserver:
    id: 0EBFCD88


- name: Pre install Docker - add repo
  become: yes
  become_user: root
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distro }} stable
    state: present


- name: Install - add Docker
  become: yes
  become_user: root
  apt:
    name: docker-ce
    update_cache: yes
    state: present
