---

- name: add repo for gcloud
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main
    state: present
  become: true
  become_user: root

- name: Upgrade apt cache
  apt:
    update_cache: yes
  become: yes
  become_user: root