---
# tasks file for setup_git

- name: Configure git
  git_config:
    name: "{{item.name}}"
    scope: global
    value: "{{item.value}}"
  with_items:
    - { name: 'user.name', value: "{{ git_user_name }}"}
    - { name: 'core.editor', value: "{{ cli_editor }}"}
    - { name: 'user.email', value: "{{ user_mail }}"}
