---
# tasks file for setup_git

- name: Configure git
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: 'user.name', value: "{{ gitUserName }}" }
    - { name: 'core.editor', value: "{{ cliEditor }}" }
    - { name: 'user.email', value: "{{ userMail }}" }
